In [7]:
import numpy as np

In [7]:
# 1 차원
a = np.array([1,2,3])
print("값 : ",a," 차원 : ",a.ndim)

값 :  [1 2 3]  차원 :  1


In [8]:
# 2차원
a = np.array([[1,2,3],[4,5,6]])
print("값 : ",a," 차원 : ",a.ndim)

값 :  [[1 2 3]
 [4 5 6]]  차원 :  2


In [9]:
a = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print("값 : ",a," 차원 : ",a.ndim)

값 :  [[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]  차원 :  3


In [10]:
arr = np.array([5,3,2])
print('shape : ', arr.shape)
print('ndim : ', arr.ndim)
print('dtype : ', arr.dtype)
print('dtype.name : ', arr.dtype.name)
print('size : ', arr.size)

shape :  (3,)
ndim :  1
dtype :  int32
dtype.name :  int32
size :  3


In [11]:
a1 = np.array([1,2,3,4,5])
print(a1, type(a1))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [12]:
a2 = np.ndarray((2,2))
print(a2,type(a2))

[[3.18299369e-313 4.45619116e-313]
 [1.08221785e-312 1.20953760e-312]] <class 'numpy.ndarray'>


In [13]:
a3 = np.ones(3)
print(a3,type(a3))
a31 =  np.ones((3,4))
print(a31,type(a31))

[1. 1. 1.] <class 'numpy.ndarray'>
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] <class 'numpy.ndarray'>


In [14]:
a4 = np.zeros(3)
print(a4,type(a4))
a41 = np.zeros((3,3))
print(a41, type(a41))

[0. 0. 0.] <class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'>


In [15]:
a5 = np.empty(3)
print(a5,type(a5))
a51 = np.empty((3,3))
print(a51,type(a51))

[0. 0. 0.] <class 'numpy.ndarray'>
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]] <class 'numpy.ndarray'>


In [48]:
a6  = np.eye(3)
print(a6, type(a6))
a61 = np.eye(3, k= -1)
print(a61, type(a61))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] <class 'numpy.ndarray'>
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]] <class 'numpy.ndarray'>


In [47]:
a7 = np.identity(5)
print(a7, type(a7))

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]] <class 'numpy.ndarray'>


In [18]:
a8 = np.linspace(1,5,10)
print(a8,type(a8))

[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ] <class 'numpy.ndarray'>


In [51]:
sample_list = [1,2,3,4,5,6]
trans_nd = np.asarray(sample_list)
print(trans_nd)
print(type(sample_list), type(trans_nd))

[1 2 3 4 5 6]
<class 'list'> <class 'numpy.ndarray'>


In [20]:
loop_ex = np.array([1,2,3])
loop_ex1 = loop_ex * 4 +1
print('loop_ex : ', loop_ex)
print('loop_ex1 : ', loop_ex1)

loop_ex :  [1 2 3]
loop_ex1 :  [ 5  9 13]


In [21]:
loop_ex = np.array([[1,2,3],[4,5,6]])
loop_ex1 = loop_ex * 4 +1
print('loop_ex : ', loop_ex)
print('loop_ex1 : ', loop_ex1)

loop_ex :  [[1 2 3]
 [4 5 6]]
loop_ex1 :  [[ 5  9 13]
 [17 21 25]]


In [22]:
nd1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(nd1)
print('1 row get :', nd1[1])
print('1 column get : ', nd1[:,1])
print('(1,2) row + column get :', nd1[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 row get : [4 5 6]
1 column get :  [2 5 8]
(1,2) row + column get : 6


In [23]:
nd1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(nd1)
print('1 row get :', nd1[1])
print('1 column get : ', nd1[:,1])
print('[1:,2:] get :', nd1[1:,:2])
print('(1,2) row + column get :', nd1[1,2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1 row get : [4 5 6]
1 column get :  [2 5 8]
[1:,2:] get : [[4 5]
 [7 8]]
(1,2) row + column get : 6


In [24]:
nd2 = np.random.randint(1,99,10)
print(nd2)
print(nd2[3:5])
nd2[3:5] = 11
print(nd2)

[18 86 51 52 72 19 50 53 65 23]
[52 72]
[18 86 51 11 11 19 50 53 65 23]


In [25]:
nd1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(nd1)
print('[1:,2:] get :', nd1[1:,:2])
nd1[1:,:2] = 0
print(nd1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1:,2:] get : [[4 5]
 [7 8]]
[[1 2 3]
 [0 0 6]
 [0 0 9]]


In [26]:
nd3 = np.random.randint(1,99,10)
print(nd3)
nd31 = nd3 > 50
print(nd31)
print(nd3[nd31])
print(nd3[nd3 > 50])
nd3[nd3 >50] = 0
print(nd3)

[38 51 55 70 36 49 72 86 70 16]
[False  True  True  True False False  True  True  True False]
[51 55 70 72 86 70]
[51 55 70 72 86 70]
[38  0  0  0 36 49  0  0  0 16]


In [27]:
nd4 = np.array([[1,2],[3,4]])
nd5 = np.array([[5,6],[7,8]])
print(nd4,type(nd4))
print(nd5,type(nd5))
print(nd4+nd5)
print(nd4-nd5)
print(nd4*nd5)
print(nd4/nd5)

[[1 2]
 [3 4]] <class 'numpy.ndarray'>
[[5 6]
 [7 8]] <class 'numpy.ndarray'>
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [28]:
nd4 = np.matrix([[1,2],[3,4]])
nd5 = np.matrix([[5,6],[7,8]])
print(nd4,type(nd4))
print(nd5,type(nd5))
print(nd4+nd5)
print(nd4-nd5)
print(nd4*nd5)
print(nd4/nd5)

[[1 2]
 [3 4]] <class 'numpy.matrix'>
[[5 6]
 [7 8]] <class 'numpy.matrix'>
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[19 22]
 [43 50]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [29]:
nd4 = np.array([[1,2],[3,4]])
nd5 = np.array([[5,6],[7,8]])
print(nd4)
print(nd5)
print(nd4.dot(nd5))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]


In [30]:
nd4 = np.matrix([[1,2],[3,4]])
nd5 = np.matrix([[5,6],[7,8]])
print(nd4)
print(nd5)
print(nd4.dot(nd5))
print(nd4*nd5)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [31]:
nd4 = np.matrix([[1,2],[3,4]])
print(nd4)
print('sum :',np.sum(nd4))
print('axis 0 sum :',np.sum(nd4,axis=0))
print('axis 0 sum :',np.sum(nd4,axis=1))

[[1 2]
 [3 4]]
sum : 10
axis 0 sum : [[4 6]]
axis 0 sum : [[3]
 [7]]


In [32]:
nd6 = np.arange(0,24).reshape([2,3,4])
print(nd6)
print(nd6.sum(axis=0))
print(nd6.sum(axis=1))
print(nd6.sum(axis=2))

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[[12 15 18 21]
 [48 51 54 57]]
[[ 6 22 38]
 [54 70 86]]


In [33]:
nd6_1 = nd6.reshape([4,6])
print(nd6_1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [34]:
nd7 = np.array([1,2,3])
nd8 = np.array([4,5,6])
print(nd7, nd7.shape)
print(nd8, nd8.shape)
print(np.inner(nd7,nd8))
print(np.dot(nd7,nd8.T))

[1 2 3] (3,)
[4 5 6] (3,)
32
32


In [35]:
nd7 = np.array([[1,2,3],[4,5,6]])
nd8 = np.array([[4,3,2],[1,5,6],[4,3,2],[1,5,6]])
print(nd7, nd7.shape)
print(nd8, nd8.shape)
print(np.inner(nd7,nd8))
print(np.dot(nd7,nd8.T))

[[1 2 3]
 [4 5 6]] (2, 3)
[[4 3 2]
 [1 5 6]
 [4 3 2]
 [1 5 6]] (4, 3)
[[16 29 16 29]
 [43 65 43 65]]
[[16 29 16 29]
 [43 65 43 65]]


In [36]:
nd7 = np.array([1,2,3])
nd8 = np.array([4,5,6])
print(nd7, nd7.shape)
print(nd8, nd8.shape)
print('outer : ', np.outer(nd7,nd8))
print('cross : ', np.cross(nd7,nd8))

[1 2 3] (3,)
[4 5 6] (3,)
outer :  [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]
cross :  [-3  6 -3]


In [37]:
nd7 = np.array([[1,2,3],[4,5,6]])
nd8 = np.array([[4,3,2],[1,5,6]])
print(nd8, nd8.shape)
print('outer : ', np.outer(nd7,nd8))
print('cross : ', np.cross(nd7,nd8))

[[4 3 2]
 [1 5 6]] (2, 3)
outer :  [[ 4  3  2  1  5  6]
 [ 8  6  4  2 10 12]
 [12  9  6  3 15 18]
 [16 12  8  4 20 24]
 [20 15 10  5 25 30]
 [24 18 12  6 30 36]]
cross :  [[ -5  10  -5]
 [  0 -18  15]]


In [39]:
nd9 = np.random.randint(-10,10,5)
print(nd9)
print(np.abs(nd9))
si = np.sign(nd9)
print(si)
print(np.abs(nd9) * si)

[-6  7  1 -5  4]
[6 7 1 5 4]
[-1  1  1 -1  1]
[-6  7  1 -5  4]


In [40]:
f1 = np.random.randint(1,10,5)
print(f1)
print(np.square(f1))
print(np.sqrt(f1))
print(np.power(f1,2))
print(np.hypot(f1,np.square(f1)))

[6 8 2 2 1]
[36 64  4  4  1]
[2.44948974 2.82842712 1.41421356 1.41421356 1.        ]
[36 64  4  4  1]
[36.49657518 64.49806199  4.47213595  4.47213595  1.41421356]


In [75]:
f2 = np.random.randn(5)
f2 = f2*10
print(f2)
print(np.ceil(f2))
print(np.floor(f2))
print(np.rint(f2))


[-17.13994247  10.96892164  -5.95080254   8.5150734   -7.53020043]
[-17.  11.  -5.   9.  -7.]
[-18.  10.  -6.   8.  -8.]
[-17.  11.  -6.   9.  -8.]


In [78]:
f3 = np.random.randint(1,100,5)
f4 = np.random.randint(1,10,5)
print(f3)
print(f4)
print('add : ',np.add(f3,f4))
print('subtract : ',np.subtract(f3,f4))
print('multiply : ',np.multiply(f3,f4))
print('divide : ',np.divide(f3,f4))
print('mod : ',np.mod(f3,f4))

[83 49 40 33 83]
[9 8 7 6 7]
add :  [92 57 47 39 90]
subtract :  [74 41 33 27 76]
multiply :  [747 392 280 198 581]
divide :  [ 9.22222222  6.125       5.71428571  5.5        11.85714286]
mod :  [2 1 5 3 6]


In [82]:
f5 = np.random.randint(0,5,5)
print(f5)
print(np.any(f5))
print(np.all(f5))

[3 0 4 1 3]
True
False


In [83]:
f5 = np.random.randint(0,5,5)
f6 = np.random.randint(0,5,5)
print(f5)
print(f6)
f7 = np.equal(f5,f6)
print(f7)
print(np.any(f7))
print(np.all(f7))

[0 3 2 4 0]
[0 0 0 1 1]
[ True False False False False]
True
False


In [41]:
f8 = np.random.randint(-10,10,10)
print(f8)
print(np.where(f8 == 0, 0, np.where(f8>0,1,-1)))
print(np.sign(f8))

[ 0  3  0 -8 -1  1 -2 -8 -5 -6]
[ 0  1  0 -1 -1  1 -1 -1 -1 -1]
[ 0  1  0 -1 -1  1 -1 -1 -1 -1]


In [93]:
f9 = np.arange(9.).reshape(3,3)
print(f9)
print(np.where(f9 > 5))
print(f9[np.where(f9 > 3.0)])
print(np.where(f9 <5, f9, -1))

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]
(array([2, 2, 2], dtype=int64), array([0, 1, 2], dtype=int64))
[4. 5. 6. 7. 8.]
[[ 0.  1.  2.]
 [ 3.  4. -1.]
 [-1. -1. -1.]]


In [101]:
f10 = np.random.randint(1,10,5)
f11 = np.random.randint(1,5,3)
print(f10)
f10u = np.unique(f10)
print(f10u)
print(f11)
print('in1d :', np.in1d(f11,f10u))
print('union1d :',np.union1d(f11,f10u))
print('intersect1d :',np.intersect1d(f11,f10u))
print('setdiff1d :',np.setdiff1d(f11,f10u))
print('setxor1d :',np.setxor1d(f11,f10u))

[7 4 4 3 2]
[2 3 4 7]
[4 4 2]
in1d : [ True  True  True]
union1d : [2 3 4 7]
intersect1d : [2 4]
setdiff1d : []
setxor1d : [3 7]


In [46]:
c2 = np.arange(1,5)
c3 = np.arange(5,9)
c4 = np.arange(9,11)
c5 = np.array((c2,c3,c4))
print(c2)
print(c3)
print(c4)
print(c5)
print(np.concatenate((c2,c3,c4)))
print(np.concatenate(c5))

[1 2 3 4]
[5 6 7 8]
[ 9 10]
[array([1, 2, 3, 4]) array([5, 6, 7, 8]) array([ 9, 10])]
[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [43]:
c6 = np.concatenate(c5)
c7 = c6 + 5
print(c6)
print(c7)
c6 = c6.reshape(2,5)
c7 = c7.reshape(2,5)
print(c6)
print(c7)
print(np.concatenate((c6,c7)))
print(np.concatenate((c6,c7),axis=1))

[ 1  2  3  4  5  6  7  8  9 10]
[ 6  7  8  9 10 11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
[[ 1  2  3  4  5  6  7  8  9 10]
 [ 6  7  8  9 10 11 12 13 14 15]]


In [44]:
save_arr = np.ndarray((5,2))
print(save_arr)
np.save('./save_arr',save_arr)
load_arr = np.load('./save_arr.npy')
print(load_arr)

[[4.24399158e-314 8.48798317e-314]
 [1.27319747e-313 1.69759663e-313]
 [2.12199579e-313 1.48539705e-313]
 [1.90979621e-313 2.33419537e-313]
 [2.75859453e-313 3.18299369e-313]]
[[4.24399158e-314 8.48798317e-314]
 [1.27319747e-313 1.69759663e-313]
 [2.12199579e-313 1.48539705e-313]
 [1.90979621e-313 2.33419537e-313]
 [2.75859453e-313 3.18299369e-313]]
