In [0]:
import numpy as np

## 1. 행렬 - 덧셈

### 1-1. 덧셈

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [0]:
# 코드를 입력해 주세요


array([[4, 6, 8],
       [3, 5, 7]])

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [0]:
a + b

ValueError: ignored

### 1-2. Sum

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
# 코드를 입력해 주세요


array([3, 5, 7])

In [0]:
# 코드를 입력해 주세요


array([6, 9])

## 2. 행렬 - 뺄셈

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [0]:
# 코드를 입력해 주세요


array([[-2, -2, -2],
       [ 1,  1,  1]])

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [0]:
a - b

ValueError: ignored

## 3. 곱셈

일반 곱셈

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [0]:
a.shape, b.shape

((2, 3), (2, 3))

In [0]:
# 코드를 입력해 주세요


array([[ 3,  8, 15],
       [ 2,  6, 12]])

단순 곱셈과 dot product는 다릅니다. 이점 유의하세요!

In [0]:
a = np.array([[1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[3, 4, 5], 
              [1, 2, 3]])

In [0]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [0]:
a * b

ValueError: ignored

In [0]:
a = np.array([[1, 2, 3],
              [1, 2, 3], 
              [2, 3, 4]])

In [0]:
b = np.array([[1, 2],
              [3, 4],  
              [5, 6]])

In [0]:
a.shape, b.shape

((3, 3), (3, 2))

In [0]:
# 코드를 입력해 주세요


array([[22, 28],
       [22, 28],
       [31, 40]])

In [0]:
a.dot(b)

array([[22, 28],
       [22, 28],
       [31, 40]])

In [0]:
1*1 + 2*3 + 3*5

22

In [0]:
1*2 + 2*4 + 3*6

28