## 1. Numpy import 하기

In [0]:
import numpy

In [0]:
numpy

### 1-1. 별칭 (alias) 지정하기 (항상 해주세요!)

In [0]:
# 코드를 입력해 주세요


## 2. ndarray 생성하기

In [0]:
arr = # 코드를 입력해 주세요


In [0]:
arr

In [0]:
[1, 2, 3, 4]

In [0]:
type(arr)

### 2-1. list로 부터 생성하기

In [0]:
mylist1 = [1, 2, 3, 4]

In [0]:
mylist2 = [[1, 2, 3, 4], 
           [5, 6, 7, 8]]

In [0]:
arr1 = # 코드를 입력해 주세요


In [0]:
arr2 = # 코드를 입력해 주세요


### 2-2. shape확인하기

In [0]:
arr1.# 코드를 입력해 주세요


In [0]:
arr2.# 코드를 입력해 주세요


## 3. array에서의 data 타입

array에서는 list와는 다르게 1개의 **단일 데이터 타입**만 허용 됩니다.

### 3-1. list에서의 data 타입

In [0]:
mylist = [1, 3.14, '테디', '1234']

In [0]:
mylist

[1, 3.14, '테디', '1234']

In [0]:
# 코드를 입력해 주세요


3.14

In [0]:
# 코드를 입력해 주세요


'테디'

### 3-2. array에서의 data 타입 (case를 통한 연구)

### case 1. int와 float 타입이 혼재된 경우

In [0]:
arr = np.array([1, 2, 3, 3.14])

In [0]:
arr

array([1.  , 2.  , 3.  , 3.14])

### case 2. int와 float 타입이 혼재되었으나, dtype을 지정한 경우

In [0]:
arr = np.array([1, 2, 3, 3.14], dtype=int)

In [0]:
arr

array([1, 2, 3, 3])

### case 3. int와 str 타입이 혼재된 경우

In [0]:
arr = np.array([1, 3.14, '테디', '1234'])

In [0]:
arr

array(['1', '3.14', '테디', '1234'], dtype='<U32')

In [0]:
arr[0] + arr[1]

'13.14'

### case 4. int와 str 타입이 혼재되어 있고 int로 dtype을 지정한 경우

In [0]:
arr = np.array([1, 3.14, '1234'], dtype=int)

In [0]:
arr

array([   1,    3, 1234])