In [1]:
# 1 차원
a = np.array([1, 2 ,3])
print("값 : ", a, " 차원 : ", a.ndim)

값 :  [1 2 3]  차원 :  1


In [28]:
# 2 차원
a = np.array([[1,2,3],[4,5,6]])
print("값 : ", a, " 차원 : ", a.ndim)

값 :  [[1 2 3]
 [4 5 6]]  차원 :  2


In [32]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

In [8]:
a3 = np.ones(3)
print(a3, type(a3))

[1. 1. 1.] <class 'numpy.ndarray'>


In [13]:
a31 = np.ones((3,4))
print(a31, type(a31))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] <class 'numpy.ndarray'>


In [15]:
a4 = np.zeros(3)
print(a4, type(a4))

[0. 0. 0.] <class 'numpy.ndarray'>


In [16]:
loop_ex = [[1,2,3],[4,5,6]]

result = []

for i in loop_ex:
    a = []
    for j in i:
        a.append((j*4)+1)
    result.append(a)

print(result)

[[5, 9, 13], [17, 21, 25]]


In [21]:
a = np.ones(3) * np.zeros(3)

In [50]:
A = list(np.random.choice(10, 100000000))
B = list(np.random.choice(10, 100000000))

# A = [1, 2, 3, 4, 5]
# B = [2, 4, 2, 1, 4]
C = []
for i in range(len(A)):
    if A[i] > B[i]:
        C.append('A')
    else :
        C.append('B')

In [3]:
A = np.random.choice(10, 100000000)
B = np.random.choice(10, 100000000)

R = np.where(A>B, 'A', np.where(A==B, 'C', 'B'))

In [4]:
R

array(['B', 'C', 'B', ..., 'B', 'A', 'C'], dtype='<U1')

In [8]:
ac = 0
bc = 0
cc = 0

for i in R:
    if i=='A':
        ac += 1
    elif i=='B':
        bc += 1
    else:
        cc += 1

print(ac, bc, cc)
print(ac+bc+cc)

45002268 45000954 9996778
100000000


In [9]:
print((R=='A').sum(), (R=='B').sum(), (R=='C').sum())

45002268 45000954 9996778


In [14]:
real_result = []
for i in np.unique(R):
    tmp = (i, (R==i).sum())
    real_result.append(tmp)
print(real_result)

[('A', 45002268), ('B', 45000954), ('C', 9996778)]
