In [0]:
import numpy as np

## 1. 슬라이싱 (Slicing)

배열의 부분 선택 (과일을 슬라이스해서 부분만 먹듯..)

In [0]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
arr.shape

(10,)

### 1-1. index 지정하여 색인

#### 1차원 array

In [0]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# 코드를 입력해 주세요


0

In [0]:
# 코드를 입력해 주세요


5

In [0]:
arr[10]

IndexError: ignored

In [0]:
# 코드를 입력해 주세요


9

In [0]:
# 코드를 입력해 주세요


0

In [0]:
arr[-11]

IndexError: ignored

#### 2차원 array

In [0]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [0]:
arr2d.shape

(3, 4)

arr2d[행, 열]

In [0]:
# 코드를 입력해 주세요


3

In [0]:
# 코드를 입력해 주세요
    

10

### 1-2. 범위 색인

#### 1차원

index 1**이상** 끝까지

In [0]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
# 코드를 입력해 주세요


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

index 5 **미만** 까지

In [0]:
# 코드를 입력해 주세요


array([0, 1, 2, 3, 4])

index 1이상 5미만

In [0]:
# 코드를 입력해 주세요


array([1, 2, 3, 4])

#### 2차원

In [0]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

row(행)을 모두 가져오려는 경우

In [0]:
# 코드를 입력해 주세요


array([1, 2, 3, 4])

column(열)을 모두 가져오려는 경우

In [0]:
# 코드를 입력해 주세요


array([ 3,  7, 11])

부분 적으로 가져오려는 경우

In [0]:
# 코드를 입력해 주세요


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
# 코드를 입력해 주세요


array([[3, 4],
       [7, 8]])

## 2. Fancy 인덱싱

fancy 인덱싱은 범위가 아닌 **특정 index의 집합의 값을 선택하여 추출**하고 싶을 때 활용합니다.

In [0]:
arr = np.array([10, 23, 2, 7, 90, 65, 32, 66, 70])

반드시 **[추출하고 싶은 인덱스]** 꺾쇠 괄호로 묶어 주세요

변수에 지정 후 추출도 가능합니다.

In [0]:
# 코드를 입력해 주세요
idx =

In [0]:
arr[idx]

### 2-2. 2차원 array

In [0]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [0]:
# 코드를 입력해 주세요


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [0]:
# 코드를 입력해 주세요


array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12]])

## 3. Boolean 인덱싱

조건 필터링을 통하여 Boolean 값을 이용한 색인 (말이 어렵다..)

In [0]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

In [0]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

### 3-1. True와 False 값으로 색인하기

In [0]:
myTrueFalse = [True, False, True]

In [0]:
arr[myTrueFalse]

IndexError: ignored

In [0]:
myTrueFalse = # 코드를 입력해 주세요


In [0]:
arr[myTrueFalse]

array([1, 3, 5, 7])

### 3-2. 조건필터

조건 연산자를 활용하여 필터를 생성할 수 있습니다

In [0]:
arr2d > # 코드를 입력해 주세요


array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

필터를 활용하여 필터에 True 조건만 색인 합니다.

이럴 때 꺾쇠 괄호로 한 번 더 묶어만 주면 됩니다. (꺾쇠 괄호 안에 조건문 삽입) 

arr2d[**조건필터**]

In [0]:
arr2d = np.array([[1, 2, 3, 4], 
                  [5, 6, 7, 8], 
                  [9, 10, 11, 12]])

In [0]:
# 코드를 입력해 주세요


array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [0]:
# 코드를 입력해 주세요


array([1, 2, 3, 4])